LOGIN_FAILURE_SETTINGS =
    {
        5 => 60*60,
        10 => 180*60,
        15 => 'forever'
    }
SECONDS_IN_ONE_HOUR = 60 * 60

CONFIRMATION_CODES_LIFE_TIME = 3 #minutes
AUTO_AUTH_TOKEN_EXPIRED_MIN = 1 #minutes
MAX_REGENERATION_COUNT = 100
SINGLE_CODE_RETRY_COUNT = 100
